"""empty message

Revision ID: 0714f8d89a03
Revises: 4d000a856d16
Create Date: 2021-01-11 19:30:21.000160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0714f8d89a03'
down_revision = '4d000a856d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('producer', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_contract_producer'), 'contract', ['producer'], unique=False)
    op.create_foreign_key(None, 'contract', 'company', ['producer'], ['company_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_index(op.f('ix_contract_producer'), table_name='contract')
    op.drop_column('contract', 'producer')
    # ### end Alembic commands ###
