"""User updates

Revision ID: 087c5f6464c8
Revises: 54d55a5f04a8
Create Date: 2021-01-08 16:36:42.227885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087c5f6464c8'
down_revision = '54d55a5f04a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('title', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'title')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
