"""empty message

Revision ID: 1c211c90a4e7
Revises: 83a0ff001277
Create Date: 2021-01-10 18:47:53.611437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c211c90a4e7'
down_revision = '83a0ff001277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=True))
    op.drop_column('user', 'access')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
