"""empty message

Revision ID: 4d000a856d16
Revises: 61602b2f9568
Create Date: 2021-01-11 19:30:05.198348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d000a856d16'
down_revision = '61602b2f9568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contract_producer', table_name='contract')
    op.drop_constraint('contract_producer_fkey', 'contract', type_='foreignkey')
    op.drop_column('contract', 'producer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('producer', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_foreign_key('contract_producer_fkey', 'contract', 'company', ['producer'], ['company_name'])
    op.create_index('ix_contract_producer', 'contract', ['producer'], unique=False)
    # ### end Alembic commands ###
