"""empty message

Revision ID: 54d55a5f04a8
Revises: cb96dbe930d4
Create Date: 2021-01-08 15:27:16.327131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d55a5f04a8'
down_revision = 'cb96dbe930d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nom', sa.Column('nom_id', sa.Integer(), nullable=False))
    op.drop_column('nom', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nom', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('nom', 'nom_id')
    # ### end Alembic commands ###
