"""empty message

Revision ID: 5a77565c5cc6
Revises: cb148d0b6788
Create Date: 2021-01-12 07:27:45.236737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a77565c5cc6'
down_revision = 'cb148d0b6788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nom', sa.Column('deilvery_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nom', 'deilvery_id')
    # ### end Alembic commands ###
