"""empty message

Revision ID: 609aa9b6fef0
Revises: c52c498ece72
Create Date: 2021-01-08 08:29:23.999286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609aa9b6fef0'
down_revision = 'c52c498ece72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.String(length=140), nullable=True),
    sa.Column('day_nom', sa.DateTime(), nullable=True),
    sa.Column('day_nom_value', sa.Integer(), nullable=True),
    sa.Column('downstream_contract', sa.Integer(), nullable=True),
    sa.Column('downstream_ba', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edit', sa.Boolean(), nullable=True),
    sa.Column('published_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nom_day_nom'), 'nom', ['day_nom'], unique=False)
    op.create_index(op.f('ix_nom_published_time'), 'nom', ['published_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nom_published_time'), table_name='nom')
    op.drop_index(op.f('ix_nom_day_nom'), table_name='nom')
    op.drop_table('nom')
    # ### end Alembic commands ###
