"""empty message

Revision ID: 61602b2f9568
Revises: 87159993154a
Create Date: 2021-01-11 19:29:49.018480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61602b2f9568'
down_revision = '87159993154a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contract_producer', table_name='contract')
    op.drop_constraint('contract_producer_fkey', 'contract', type_='foreignkey')
    op.drop_column('contract', 'producer')
    op.add_column('nom', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nom', 'contract', ['contract_id'], ['contract_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nom', type_='foreignkey')
    op.drop_column('nom', 'contract_id')
    op.add_column('contract', sa.Column('producer', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_foreign_key('contract_producer_fkey', 'contract', 'company', ['producer'], ['company_name'])
    op.create_index('ix_contract_producer', 'contract', ['producer'], unique=False)
    # ### end Alembic commands ###
