"""empty message

Revision ID: 6bb1ed2fb593
Revises: 5a77565c5cc6
Create Date: 2021-01-12 07:45:58.036290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb1ed2fb593'
down_revision = '5a77565c5cc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nom', sa.Column('user', sa.String(length=64), nullable=True))
    op.drop_constraint('nom_user_id_fkey', 'nom', type_='foreignkey')
    op.create_foreign_key(None, 'nom', 'user', ['user'], ['username'])
    op.drop_column('nom', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nom', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'nom', type_='foreignkey')
    op.create_foreign_key('nom_user_id_fkey', 'nom', 'user', ['user_id'], ['id'])
    op.drop_column('nom', 'user')
    # ### end Alembic commands ###
