"""empty message

Revision ID: 7848fa66f358
Revises: a6913204f106
Create Date: 2021-01-11 19:20:00.556525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7848fa66f358'
down_revision = 'a6913204f106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nom', sa.Column('day_nom', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_nom_day_nom'), 'nom', ['day_nom'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nom_day_nom'), table_name='nom')
    op.drop_column('nom', 'day_nom')
    # ### end Alembic commands ###
