"""empty message

Revision ID: 83a0ff001277
Revises: 35b1e25f9c56
Create Date: 2021-01-10 18:46:03.165456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a0ff001277'
down_revision = '35b1e25f9c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access')
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=True))
    op.drop_constraint('user_access_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'access')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_access_fkey', 'user', 'access', ['access'], ['access_id'])
    op.drop_column('user', 'role')
    op.create_table('access',
    sa.Column('access_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('access_name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('access_id', name='access_pkey')
    )
    # ### end Alembic commands ###
