"""empty message

Revision ID: 8cd8a3488331
Revises: 7ead5667b647
Create Date: 2021-01-09 16:52:34.148571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd8a3488331'
down_revision = '7ead5667b647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
