"""empty message

Revision ID: 95c8a8b583c1
Revises: 
Create Date: 2021-01-11 18:30:59.736519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c8a8b583c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=True),
    sa.Column('company_type', sa.String(length=8), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_company'), 'user', ['company'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('contract',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('producer', sa.String(length=100), nullable=False),
    sa.Column('marketer', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('day_due', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['marketer'], ['company.company_name'], ),
    sa.ForeignKeyConstraint(['producer'], ['company.company_name'], ),
    sa.PrimaryKeyConstraint('contract_id', 'producer')
    )
    op.create_index(op.f('ix_contract_marketer'), 'contract', ['marketer'], unique=False)
    op.create_index(op.f('ix_contract_producer'), 'contract', ['producer'], unique=False)
    op.create_table('nom',
    sa.Column('nom_id', sa.Integer(), nullable=False),
    sa.Column('day_nom', sa.DateTime(), nullable=True),
    sa.Column('day_nom_value', sa.Integer(), nullable=True),
    sa.Column('downstream_contract', sa.Integer(), nullable=True),
    sa.Column('downstream_ba', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('edit', sa.Boolean(), nullable=True),
    sa.Column('published_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('nom_id')
    )
    op.create_index(op.f('ix_nom_day_nom'), 'nom', ['day_nom'], unique=False)
    op.create_index(op.f('ix_nom_published_time'), 'nom', ['published_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nom_published_time'), table_name='nom')
    op.drop_index(op.f('ix_nom_day_nom'), table_name='nom')
    op.drop_table('nom')
    op.drop_index(op.f('ix_contract_producer'), table_name='contract')
    op.drop_index(op.f('ix_contract_marketer'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_company'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
