"""empty message

Revision ID: a6913204f106
Revises: 95c8a8b583c1
Create Date: 2021-01-11 19:19:40.726000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6913204f106'
down_revision = '95c8a8b583c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nom_day_nom', table_name='nom')
    op.drop_column('nom', 'day_nom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nom', sa.Column('day_nom', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_nom_day_nom', 'nom', ['day_nom'], unique=False)
    # ### end Alembic commands ###
