"""empty message

Revision ID: bc8cc0d14b54
Revises: 5f9585a360a1
Create Date: 2021-01-11 19:27:57.121746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8cc0d14b54'
down_revision = '5f9585a360a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'producer',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('nom', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nom', 'contract', ['contract_id'], ['contract_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nom', type_='foreignkey')
    op.drop_column('nom', 'contract_id')
    op.alter_column('contract', 'producer',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
