"""empty message

Revision ID: c52c498ece72
Revises: 962ce7c95dcb
Create Date: 2021-01-08 08:03:14.542997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52c498ece72'
down_revision = '962ce7c95dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('company', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_company'), 'user', ['company'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_company'), table_name='user')
    op.drop_column('user', 'company')
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
