"""empty message

Revision ID: cb148d0b6788
Revises: c05624f02301
Create Date: 2021-01-12 06:59:59.628059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb148d0b6788'
down_revision = 'c05624f02301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contract', ['contract_id'])
    op.add_column('nom', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nom', 'contract', ['contract_id'], ['contract_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nom', type_='foreignkey')
    op.drop_column('nom', 'contract_id')
    op.drop_constraint(None, 'contract', type_='unique')
    # ### end Alembic commands ###
