"""empty message

Revision ID: cb96dbe930d4
Revises: 609aa9b6fef0
Create Date: 2021-01-08 08:35:49.038569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb96dbe930d4'
down_revision = '609aa9b6fef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('contract_id', sa.String(length=140), nullable=False),
    sa.Column('producer', sa.String(length=100), nullable=True),
    sa.Column('marketer', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('day_due', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index(op.f('ix_contract_marketer'), 'contract', ['marketer'], unique=False)
    op.create_index(op.f('ix_contract_producer'), 'contract', ['producer'], unique=False)
    op.create_foreign_key(None, 'nom', 'contract', ['contract_id'], ['contract_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nom', type_='foreignkey')
    op.drop_index(op.f('ix_contract_producer'), table_name='contract')
    op.drop_index(op.f('ix_contract_marketer'), table_name='contract')
    op.drop_table('contract')
    # ### end Alembic commands ###
