"""empty message

Revision ID: f9833e6d821b
Revises: 7848fa66f358
Create Date: 2021-01-11 19:24:03.201454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9833e6d821b'
down_revision = '7848fa66f358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nom', sa.Column('nom_contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nom', 'contract', ['nom_contract_id'], ['contract_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nom', type_='foreignkey')
    op.drop_column('nom', 'nom_contract_id')
    # ### end Alembic commands ###
